version: '3.5'

services:
  postgres:
    container_name: spring-data-rest-postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-data-rest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:\var\lib\postgresql\data

volumes:
  postgres-data:
